services:
#    gestion.example:
#        class: GestionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     
     GestionBundle\DataFixtures\ORM\utilisateursFixture:
         tags: [doctrine.fixture.orm]